# Generated by Django 2.0.2 on 2018-04-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('recommended_repos', models.ManyToManyField(through='offline_calculator.Recommendation', to='offline_calculator.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='recommendation',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='offline_calculator.Repository'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='offline_calculator.Repository'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('source', 'target')},
        ),
    ]
