# Generated by Django 2.0.3 on 2018-05-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'source', 'target')},
        ),
    ]
