# Generated by Django 2.0.2 on 2018-04-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='offline_calculator.Repository'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='offline_calculator.Repository'),
        ),
    ]
