# Generated by Django 2.0.5 on 2018-06-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0002_auto_20180519_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_languages',
        ),
    ]
