# Generated by Django 2.0.3 on 2018-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0003_auto_20180428_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='recommended_repos',
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='source',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='target',
            field=models.IntegerField(db_index=True),
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
