# Generated by Django 2.0.2 on 2018-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0004_auto_20180508_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('size', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('topics', models.TextField()),
                ('languages', models.TextField()),
                ('watchers_count', models.PositiveIntegerField()),
                ('forks_count', models.PositiveIntegerField()),
                ('open_issues', models.PositiveIntegerField()),
                ('subscribers_count', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'repositories',
            },
        ),
        migrations.AlterModelTable(
            name='recommendation',
            table='recommendations',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
