# Generated by Django 2.0.2 on 2018-05-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0005_auto_20180511_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='offline_calculator.Repository'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='offline_calculator.Repository'),
        ),
    ]
