# Generated by Django 2.0.2 on 2018-05-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0006_auto_20180512_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='recommended',
            field=models.ManyToManyField(through='offline_calculator.Recommendation', to='offline_calculator.Repository'),
        ),
    ]
