# Generated by Django 2.0.3 on 2018-05-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0007_auto_20180512_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRepositories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_languages',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_topics',
            field=models.TextField(null=True),
        ),
    ]
