# Generated by Django 2.0.2 on 2018-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0008_auto_20180518_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='x', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
