# Generated by Django 2.0.2 on 2018-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0009_auto_20180518_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='x'),
            preserve_default=False,
        ),
    ]
