# Generated by Django 2.0.2 on 2018-05-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offline_calculator', '0010_auto_20180518_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrepositories',
            name='repo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offline_calculator.Repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrepositories',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offline_calculator.User'),
            preserve_default=False,
        ),
    ]
